[package]
name = "runmany"
version = "0.3.0"
edition = "2021"
description = "Easily run multiple long-running commands in parallel."
license = "GPL-3.0"
repository = "https://github.com/soanvig/runmany"
readme = "README.md"
keywords = ["system", "process", "many"]

[dependencies]
colored = "2.1.0"
